package com.utsavberi.levelUpFitness.component;

import com.utsavberi.levelUpFitness.model.Exercise;
import com.utsavberi.levelUpFitness.model.Workout;
import com.utsavberi.levelUpFitness.model.WorkoutExercise;
import com.utsavberi.levelUpFitness.repository.ExerciseRepository;
import com.utsavberi.levelUpFitness.repository.WorkoutRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.Set;

@Component
public class DatabaseLoader implements CommandLineRunner {

    private final ExerciseRepository exerciseRepository;
    private final WorkoutRepository workoutRepository;


    @Autowired
    public DatabaseLoader(ExerciseRepository exerciseRepository, WorkoutRepository workoutRepository) {
        this.exerciseRepository = exerciseRepository;
        this.workoutRepository = workoutRepository;

        /*
        db reset scripts:
        /usr/local/mysql/bin $ ./mysql -u root -p dbLevelUpFitness
        password: password
        drop database dbLevelUpfitness
        create database dblevelupfitness;
        use dblevelupfitness
        */
    }

    @Override
    public void run(String... args) throws Exception {
        if (exerciseRepository.count() == 0L) {
            //name, description, points per lb
            exerciseRepository.save(addExercise("ab crunch machine", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("ab roller", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("adductor", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("adductor/groin", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("advanced kettlebell windmill", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("air bike", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("all fours quad stretch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("alternate hammer curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("alternate heel touchers", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("alternate incline dumbbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("alternate leg diagonal bound", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("alternating cable shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("alternating deltoid raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("alternating floor press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("alternating hang clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("alternating kettlebell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("alternating kettlebell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("alternating renegade row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("ankle circles", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("ankle on the knee", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("anterior tibialis-smr", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("anti-gravity press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("arm circles", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("arnold dumbbell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("around the worlds", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("atlas stone trainer", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("atlas stones", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("axle deadlift", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("ab crunch machine", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("ab roller", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("adductor", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("adductor/groin", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("advanced kettlebell windmill", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("air bike", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("all fours quad stretch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("alternate hammer curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("alternate heel touchers", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("alternate incline dumbbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("alternate leg diagonal bound", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("alternating cable shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("alternating deltoid raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("alternating floor press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("alternating hang clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("alternating kettlebell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("alternating kettlebell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("alternating renegade row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("ankle circles", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("ankle on the knee", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("anterior tibialis-smr", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("anti-gravity press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("arm circles", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("arnold dumbbell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("around the worlds", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("atlas stone trainer", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("atlas stones", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("axle deadlift", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("back flyes - with bands", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("backward drag", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("backward medicine ball throw", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("balance board", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("ball leg curl", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("band assisted pull-up", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("band good morning", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("band good morning (pull through)", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("band hip adductions", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("band pull apart", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("band skull crusher", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("barbell ab rollout", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("barbell ab rollout - on knees", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("barbell bench press - medium grip", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("barbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("barbell curls lying against an incline", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("barbell deadlift", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("barbell full squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("barbell glute bridge", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("barbell guillotine bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("barbell hack squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("barbell hip thrust", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("barbell incline bench press - medium grip", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("barbell incline shoulder raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("barbell lunge", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("barbell rear delt row", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("barbell rollout from bench", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("barbell seated calf raise", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("barbell shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("barbell shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("barbell shrug behind the back", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("barbell side bend", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("barbell side split squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("barbell squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("barbell squat to a bench", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("barbell step ups", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("barbell walking lunge", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("battling ropes", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("bear crawl sled drags", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("behind head chest stretch", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("bench dips", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("bench jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("bench press - powerlifting", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("bench press - with bands", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("bench press with chains", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("bench sprint", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("bent over barbell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("bent over dumbbell rear delt raise with head on bench", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("bent over low-pulley side lateral", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("bent over one-arm long bar row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("bent over two-arm long bar row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("bent over two-dumbbell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("bent over two-dumbbell row with palms in", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("bent press", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("bent-arm barbell pullover", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("bent-arm dumbbell pullover", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("bent-knee hip raise", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("bicycling", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("board press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("body tricep press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("body-up", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("bodyweight flyes", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("bodyweight mid row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("bodyweight squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("bodyweight walking lunge", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("bosu ball cable crunch with side bends", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("bottoms up", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("bottoms-up clean from the hang position", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("box jump (multiple response)", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("box skip", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("box squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("box squat with bands", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("box squat with chains", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("brachialis-smr", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("bradford/rocky presses", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("butt lift (bridge)", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("butt-ups", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("butterfly", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("cable chest press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("cable crossover", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("cable crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("cable deadlifts", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("cable hammer curls - rope attachment", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("cable hip adduction", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("cable incline pushdown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("cable incline triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("cable internal rotation", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("cable iron cross", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("cable judo flip", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("cable lying triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("cable one arm tricep extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("cable preacher curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("cable rear delt fly", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("cable reverse crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("cable rope overhead triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("cable rope rear-delt rows", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("cable russian twists", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("cable seated crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("cable seated lateral raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("cable shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("cable shrugs", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("cable tuck reverse crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("cable wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("calf press", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("calf press on the leg press machine", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("calf raise on a dumbbell", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("calf raises - with bands", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("calf stretch elbows against wall", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("calf stretch hands against wall", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("calf-machine shoulder shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("calves-smr", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("car deadlift", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("car drivers", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("carioca quick step", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("cat stretch", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("catch and overhead throw", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("chain handle extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("chain press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("chair leg extended stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("chair lower back stretch", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("chair squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("chair upper body stretch", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("chest and front of shoulder stretch", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("chest push (multiple response)", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("chest push (single response)", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("chest push from 3 point stance", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("chest push with run release", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("chest stretch on stability ball", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("child's pose", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("chin to chest stretch", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("chin-up", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("circus bell", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("clean and jerk", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("clean and press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("clean deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("clean from blocks", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("clean pull", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("clean shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("clock push-up", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("close-grip barbell bench press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("close-grip dumbbell press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("close-grip ez bar curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("close-grip ez-bar curl with band", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("close-grip ez-bar press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("close-grip front lat pulldown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("close-grip push-up off of a dumbbell", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("close-grip standing barbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("cocoons", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("conan's wheel", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("concentration curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("cross body hammer curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("cross over - with bands", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("cross-body crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("crossover reverse lunge", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("crucifix", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("crunch - hands overhead", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("crunch - legs on exercise ball", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("crunches", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("cuban press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dancer's stretch", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("deadlift with bands", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("deadlift with chains", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("decline barbell bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("decline close-grip bench to skull crusher", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("decline crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("decline dumbbell bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("decline dumbbell flyes", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("decline dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("decline ez bar triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("decline oblique crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("decline push-up", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("decline reverse crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("decline smith press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("deficit deadlift", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("depth jump leap", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("dip machine", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("dips - chest version", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("dips - triceps version", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("donkey calf raises", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("double kettlebell alternating hang clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("double kettlebell jerk", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("double kettlebell push press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("double kettlebell snatch", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("double kettlebell windmill", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("double leg butt kick", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("downward facing balance", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("drag curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("drop push", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("dumbbell alternate bicep curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("dumbbell bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("dumbbell bench press with neutral grip", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("dumbbell bicep curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("dumbbell clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("dumbbell floor press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("dumbbell flyes", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("dumbbell incline row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("dumbbell incline shoulder raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell lunges", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("dumbbell lying one-arm rear lateral raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell lying pronation", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("dumbbell lying rear lateral raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell lying supination", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("dumbbell one-arm shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell one-arm triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("dumbbell one-arm upright row", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell prone incline curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("dumbbell raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell rear lunge", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("dumbbell scaption", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell seated box jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("dumbbell seated one-leg calf raise", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("dumbbell shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("dumbbell shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("dumbbell side bend", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("dumbbell squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("dumbbell squat to a bench", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("dumbbell step ups", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("dumbbell tricep extension -pronated grip", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("dynamic back stretch", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("dynamic chest stretch", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("elbow circles", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("elbow to knee", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("elbows back", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("elevated back lunge", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("elevated cable rows", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("elliptical trainer", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("exercise ball crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("exercise ball pull-in", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("extended range one-arm kettlebell floor press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("external rotation", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("external rotation with band", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("external rotation with cable", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("ez-bar curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("ez-bar skullcrusher", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("face pull", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("farmer's walk", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("fast skipping", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("finger curls", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("flat bench cable flyes", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("flat bench leg pull-in", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("flat bench lying leg raise", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("flexor incline dumbbell curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("floor glute-ham raise", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("floor press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("floor press with chains", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("flutter kicks", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("foot-smr", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("forward drag with press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("frankenstein squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("freehand jump squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("frog hops", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("frog sit-ups", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("front barbell squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("front barbell squat to a bench", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("front box jump", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("front cable raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("front cone hops (or hurdle hops)", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("front dumbbell raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("front incline dumbbell raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("front leg raises", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("front plate raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("front raise and pullover", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("front squat (clean grip)", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("front squats with two kettlebells", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("front two-dumbbell raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("full range-of-motion lat pulldown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("gironda sternum chins", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("glute ham raise", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("glute kickback", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("goblet squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("good morning", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("good morning off pins", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("gorilla chin/crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("groin and back stretch", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("groiners", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("hack squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("hammer curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("hammer grip incline db bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("hamstring stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("hamstring-smr", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("handstand push-ups", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("hang clean", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("hang clean - below the knees", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("hang snatch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("hang snatch - below knees", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("hanging bar good morning", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("hanging leg raise", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("hanging pike", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("heaving snatch balance", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("heavy bag thrust", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("high cable curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("hip circles (prone)", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("hip extension with bands", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("hip flexion with band", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("hip lift with band", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("hug a ball", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("hug knees to chest", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("hurdle hops", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("hyperextensions (back extensions)", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("hyperextensions with no hyperextension bench", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("iliotibial tract-smr", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("incline barbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("incline bench pull", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("incline cable chest press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline cable flye", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline dumbbell bench with palms facing in", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline dumbbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("incline dumbbell flyes", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline dumbbell flyes - with a twist", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline dumbbell press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline hammer curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("incline inner biceps curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("incline push-up", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline push-up close-grip", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("incline push-up depth jump", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline push-up medium", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline push-up reverse grip", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("incline push-up wide", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("intermediate groin stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("intermediate hip flexor and quad stretch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("internal rotation with band", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("inverted row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("inverted row with straps", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("iron cross", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("iron crosses (stretch)", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("isometric chest squeezes", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("isometric neck exercise - front and back", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("isometric neck exercise - sides", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("isometric wipers", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("it band and glute stretch", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("jackknife sit-up", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("janda sit-up", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("jefferson squats", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("jerk balance", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("jerk dip squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("jm press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("jogging-treadmill", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("keg load", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("kettlebell arnold press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kettlebell dead clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("kettlebell figure 8", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("kettlebell hang clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("kettlebell one-legged deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("kettlebell pass between the legs", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("kettlebell pirate ships", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kettlebell pistol squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("kettlebell seated press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kettlebell seesaw press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kettlebell sumo high pull", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("kettlebell thruster", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kettlebell turkish get-up (lunge style)", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kettlebell turkish get-up (squat style)", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kettlebell windmill", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("kipping muscle up", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("knee across the body", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("knee circles", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("knee tuck jump", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("knee/hip raise on parallel bars", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("kneeling arm drill", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("kneeling cable crunch with alternating oblique twists", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("kneeling cable triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("kneeling forearm stretch", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("kneeling high pulley row", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("kneeling hip flexor", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("kneeling jump squat", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("kneeling single-arm high pulley row", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("kneeling squat", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("landmine 180's", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("landmine linear jammer", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("lateral bound", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("lateral box jump", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("lateral cone hops", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("lateral raise - with bands", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("latissimus dorsi-smr", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("leg extensions", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("leg lift", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("leg press", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("leg pull-in", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("leg-over floor press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("leg-up hamstring stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("leverage chest press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("leverage deadlift", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("leverage decline chest press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("leverage high row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("leverage incline chest press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("leverage iso row", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("leverage shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("leverage shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("linear 3-part start technique", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("linear acceleration wall drill", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("linear depth jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("log lift", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("london bridges", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("looking at ceiling", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("low cable crossover", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("low cable triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("low pulley row to neck", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("lower back curl", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("lower back-smr", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("lunge pass through", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("lunge sprint", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("lying bent leg groin", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("lying cable curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("lying cambered barbell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("lying close-grip bar curl on high pulley", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("lying close-grip barbell triceps extension behind the head", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("lying close-grip barbell triceps press to chin", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("lying crossover", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("lying dumbbell tricep extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("lying face down plate neck resistance", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("lying face up plate neck resistance", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("lying glute", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("lying hamstring", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("lying high bench barbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("lying leg curls", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("lying machine squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("lying one-arm lateral raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("lying prone quadriceps", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("lying rear delt raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("lying supine dumbbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("lying t-bar row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("lying triceps press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("machine bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("machine bicep curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("machine preacher curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("machine shoulder (military) press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("machine triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("medicine ball chest pass", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("medicine ball full twist", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("medicine ball scoop throw", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("middle back shrug", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("middle back stretch", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("mixed grip chin", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("monster walk", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("mountain climbers", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("moving claw series", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("muscle snatch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("muscle up", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("narrow stance hack squats", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("narrow stance leg press", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("narrow stance squats", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("natural glute ham raise", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("neck press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("neck-smr", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("oblique crunches", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("oblique crunches - on the floor", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("olympic squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("on your side quad stretch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("on-your-back quad stretch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("one arm against wall", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("one arm chin-up", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("one arm dumbbell bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("one arm dumbbell preacher curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("one arm floor press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("one arm lat pulldown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("one arm pronated dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("one arm supinated dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("one half locust", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("one handed hang", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("one knee to chest", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("one leg barbell squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("one-arm dumbbell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("one-arm flat bench dumbbell flye", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("one-arm high-pulley cable side bends", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("one-arm incline lateral raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("one-arm kettlebell clean and jerk", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell floor press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("one-arm kettlebell jerk", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell military press to the side", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell para press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell push press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("one-arm kettlebell snatch", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell split jerk", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell split snatch", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-arm kettlebell swings", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("one-arm long bar row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("one-arm medicine ball slam", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("one-arm open palm kettlebell clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("one-arm overhead kettlebell squats", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("one-arm side deadlift", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("one-arm side laterals", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("one-legged cable kickback", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("open palm kettlebell clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("otis-up", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("overhead cable curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("overhead lat", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("overhead slam", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("overhead squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("overhead stretch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("overhead triceps", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("pallof press with rotation", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("palms-down dumbbell wrist curl over a bench", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("palms-down wrist curl over a bench", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("palms-up barbell wrist curl over a bench", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("palms-up dumbbell wrist curl over a bench", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("parallel bar dip", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("pelvic tilt into bridge", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("peroneals stretch", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("peroneals-smr", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("physioball hip bridge", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("pin presses", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("piriformis-smr", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("plank", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("plank with twist", "", 100.0f, ""));
            exerciseRepository.save(addExercise("plate pinch", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("plate twist", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("platform hamstring slides", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("plie dumbbell squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("plyo kettlebell pushups", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("plyo push-up", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("posterior tibialis stretch", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("power clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("power clean from blocks", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("power jerk", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("power partials", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("power snatch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("power snatch from blocks", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("power stairs", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("preacher curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("preacher hammer dumbbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("press sit-up", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("prone manual hamstring", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("prowler sprint", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("pull through", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("pullups", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("push press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("push press - behind the neck", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("push up to side plank", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("push-up wide", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("push-ups - close triceps position", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("push-ups with feet elevated", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("push-ups with feet on an exercise ball", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("pushups", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("pushups (close and wide hand positions)", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("pyramid", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("quad stretch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("quadriceps-smr", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("quick leap", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("rack delivery", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("rack pull with bands", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("rack pulls", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("rear leg raises", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("recumbent bike", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("return push from stance", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("reverse band bench press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("reverse band box squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("reverse band deadlift", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("reverse band power squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("reverse band sumo deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("reverse barbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("reverse barbell preacher curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("reverse cable curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("reverse crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("reverse flyes", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("reverse flyes with external rotation", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("reverse grip bent-over rows", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("reverse grip triceps pushdown", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("reverse hyperextension", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("reverse machine flyes", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("reverse plate curls", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("reverse triceps bench press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("rhomboids-smr", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("rickshaw carry", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("rickshaw deadlift", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("ring dips", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("rocket jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("rocking standing calf raise", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("rocky pull-ups/pulldowns", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("romanian deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("romanian deadlift from deficit", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("rope climb", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("rope crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("rope jumping", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("rope straight-arm pulldown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("round the world shoulder stretch", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("runner's stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("russian twist", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("sandbag load", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("scapular pull-up", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("scissor kick", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("scissors jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("seated band hamstring curl", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("seated barbell military press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("seated barbell twist", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("seated bent-over one-arm dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("seated bent-over rear delt raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("seated bent-over two-arm dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("seated biceps", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("seated cable rows", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("seated cable shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("seated calf raise", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("seated calf stretch", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("seated close-grip concentration barbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("seated dumbbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("seated dumbbell inner biceps curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("seated dumbbell palms-down wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("seated dumbbell palms-up wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("seated dumbbell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("seated flat bench leg pull-in", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("seated floor hamstring stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("seated front deltoid", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("seated glute", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("seated good mornings", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("seated hamstring", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("seated hamstring and calf stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("seated head harness neck resistance", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("seated leg curl", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("seated leg tucks", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("seated one-arm cable pulley rows", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("seated one-arm dumbbell palms-down wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("seated one-arm dumbbell palms-up wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("seated overhead stretch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("seated palm-up barbell wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("seated palms-down barbell wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("seated side lateral raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("seated triceps press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("seated two-arm palms-up low-pulley wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("see-saw press (alternating side press)", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("shotgun row", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("shoulder circles", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("shoulder press - with bands", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("shoulder raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("shoulder stretch", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("side bridge", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("side hop-sprint", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("side jackknife", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("side lateral raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("side laterals to front raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("side leg raises", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("side lying groin stretch", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("side neck stretch", "", 100.0f, "neck"));
            exerciseRepository.save(addExercise("side standing long jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("side to side box shuffle", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("side to side chins", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("side wrist pull", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("side-lying floor stretch", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("single dumbbell raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("single leg butt kick", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("single leg glute bridge", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("single leg push-off", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("single-arm cable crossover", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("single-arm linear jammer", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("single-arm push-up", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("single-cone sprint drill", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("single-leg high box squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("single-leg hop progression", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("single-leg lateral hop", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("single-leg leg extension", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("single-leg stride jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("sit squats", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("sit-up", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("skating", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("sled drag - harness", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("sled overhead backward walk", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("sled overhead triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("sled push", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("sled reverse flye", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("sled row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("sledgehammer swings", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("smith incline shoulder raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("smith machine behind the back shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("smith machine bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("smith machine bent over row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("smith machine calf raise", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("smith machine close-grip bench press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("smith machine decline press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("smith machine hang power clean", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("smith machine hip raise", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("smith machine incline bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("smith machine leg press", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("smith machine one-arm upright row", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("smith machine overhead shoulder press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("smith machine pistol squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("smith machine reverse calf raises", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("smith machine shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("smith machine squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("smith machine stiff-legged deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("smith machine upright row", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("smith single-leg split squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("snatch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("snatch balance", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("snatch deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("snatch from blocks", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("snatch pull", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("snatch shrug", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("speed band overhead triceps", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("speed band pushdown", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("speed box squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("speed squats", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("spell caster", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("spider crawl", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("spider curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("spinal stretch", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("split clean", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("split jerk", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("split jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("split snatch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("split squat with dumbbells", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("split squats", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("squat jerk", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("squat with bands", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("squat with chains", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("squat with plate movers", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("squats - with bands", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("stairmaster", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("standing alternating dumbbell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing barbell calf raise", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("standing barbell press behind neck", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing bent-over one-arm dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("standing bent-over two-arm dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("standing biceps cable curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("standing biceps stretch", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("standing bradford press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing cable chest press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("standing cable lift", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("standing cable wood chop", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("standing calf raises", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("standing concentration curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("standing dumbbell calf raise", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("standing dumbbell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing dumbbell reverse curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("standing dumbbell straight-arm front delt raise above head", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("standing dumbbell upright row", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("standing elevated quad stretch", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("standing front barbell raise over head", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing gastrocnemius calf stretch", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("standing hamstring and calf stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("standing hip circles", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("standing hip flexors", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("standing inner-biceps curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("standing lateral stretch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("standing leg curl", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("standing long jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("standing low-pulley deltoid raise", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing low-pulley one-arm triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("standing military press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing olympic plate hand squeeze", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("standing one-arm cable curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("standing one-arm dumbbell curl over incline bench", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("standing one-arm dumbbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("standing overhead barbell triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("standing palm-in one-arm dumbbell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing palms-in dumbbell press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("standing palms-up barbell behind the back wrist curl", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("standing pelvic tilt", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("standing rope crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("standing soleus and achilles stretch", "", 100.0f, "calves"));
            exerciseRepository.save(addExercise("standing toe touches", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("standing towel triceps extension", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("standing two-arm overhead throw", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("star jump", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("step mill", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("step-up with knee raise", "", 100.0f, "glutes"));
            exerciseRepository.save(addExercise("stiff leg barbell good morning", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("stiff-legged barbell deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("stiff-legged dumbbell deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("stomach vacuum", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("straight bar bench mid rows", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("straight raises on incline bench", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("straight-arm dumbbell pullover", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("straight-arm pulldown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("stride jump crossover", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("sumo deadlift", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("sumo deadlift with bands", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("sumo deadlift with chains", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("superman", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("supine chest throw", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("supine one-arm overhead throw", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("supine two-arm overhead throw", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("suspended push-up", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("suspended reverse crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("suspended row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("suspended split squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("t-bar row with handle", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("tate press", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("the straddle", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("thigh abductor", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("thigh adductor", "", 100.0f, "adductors"));
            exerciseRepository.save(addExercise("tire flip", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("toe touchers", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("torso rotation", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("trail running/walking", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("trap bar deadlift", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("tricep dumbbell kickback", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("tricep side stretch", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("triceps overhead extension with rope", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("triceps pushdown", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("triceps pushdown - rope attachment", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("triceps pushdown - v-bar attachment", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("triceps stretch", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("tuck crunch", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("two-arm dumbbell preacher curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("two-arm kettlebell clean", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("two-arm kettlebell jerk", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("two-arm kettlebell military press", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("two-arm kettlebell row", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("underhand cable pulldowns", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("upper back stretch", "", 100.0f, "middle back"));
            exerciseRepository.save(addExercise("upper back-leg grab", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("upright barbell row", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("upright cable row", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("upright row - with bands", "", 100.0f, "traps"));
            exerciseRepository.save(addExercise("upward stretch", "", 100.0f, "shoulders"));
            exerciseRepository.save(addExercise("v-bar pulldown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("v-bar pullup", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("vertical swing", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("weighted ball hyperextension", "", 100.0f, "lower back"));
            exerciseRepository.save(addExercise("weighted ball side bend", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("weighted bench dip", "", 100.0f, "triceps"));
            exerciseRepository.save(addExercise("weighted crunches", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("weighted jump squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("weighted pull ups", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("weighted sissy squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("weighted sit-ups - with bands", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("weighted squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("wide stance barbell squat", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("wide stance stiff legs", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("wide-grip barbell bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("wide-grip decline barbell bench press", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("wide-grip decline barbell pullover", "", 100.0f, "chest"));
            exerciseRepository.save(addExercise("wide-grip lat pulldown", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("wide-grip pulldown behind the neck", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("wide-grip rear pull-up", "", 100.0f, "lats"));
            exerciseRepository.save(addExercise("wide-grip standing barbell curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("wind sprints", "", 100.0f, "abdominals"));
            exerciseRepository.save(addExercise("windmills", "", 100.0f, "abductors"));
            exerciseRepository.save(addExercise("world's greatest stretch", "", 100.0f, "hamstrings"));
            exerciseRepository.save(addExercise("wrist circles", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("wrist roller", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("wrist rotations with straight bar", "", 100.0f, "forearms"));
            exerciseRepository.save(addExercise("yoke walk", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("zercher squats", "", 100.0f, "quadriceps"));
            exerciseRepository.save(addExercise("zottman curl", "", 100.0f, "biceps"));
            exerciseRepository.save(addExercise("zottman preacher curl", "", 100.0f, "biceps"));        }
            //Push Exercise
//        addPushExercise();
//        addPullExercise();
//        addLegsExercise();
    }

    private void addLegsExercise() {
        Set<WorkoutExercise> list = new HashSet<>();

        list.add(addWorkoutExercise("Squats", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));
        list.add(addWorkoutExercise("RDL", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));
        list.add(addWorkoutExercise("Extensions", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));

        Workout workout = new Workout("Legs", false);
        workout.setWorkoutExercises(list);
        workoutRepository.save(workout);
    }

    private void addPullExercise() {
        Set<WorkoutExercise> list = new HashSet<>();

        list.add(addWorkoutExercise("Squats", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));
        list.add(addWorkoutExercise("RDL", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));
        list.add(addWorkoutExercise("Extensions", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));

        Workout workout = new Workout("Pull", false);
        workout.setWorkoutExercises(list);
        workoutRepository.save(workout);
    }

    private void addPushExercise() {
        Set<WorkoutExercise> list = new HashSet<>();

        list.add(addWorkoutExercise("Squats", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));
//        list.add(addExercise("RDL", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));
//        list.add(addExercise("Extensions", "upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", 100));

        Workout workout = new Workout("Push", false);
        workout.setWorkoutExercises(list);
        workoutRepository.save(workout);
    }

    private WorkoutExercise addWorkoutExercise(String name, String description, float pointsPerRepPerLbs) {
        return
                new WorkoutExercise(addExercise(
                        name,
                        description,
                        pointsPerRepPerLbs, "chest"),3, 10, 60);
    }

    private Exercise addExercise(String name, String description, float pointsPerRepPerLbs, String primaryMuscleUsed) {
        return new Exercise(
                name,
                description,
                pointsPerRepPerLbs, primaryMuscleUsed);
    }
}
